anchor_version = "0.28.0"
solana_version = "1.16.18"

[features]
seeds = false

[toolchain]
anchor_version = "0.28.0"  # `anchor-cli` version to use
solana_version = "1.16.18" # Solana version to use

[provider]
cluster = "localnet"
wallet = "./keys/localnet/owner.json"

[programs.mainnet]
spl_governance = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
spl_stake_pool = "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"
spl_token = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
spl_token_2022 = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
